# This script should (I think) import all of the individual modules (loader,
# visualizer, featurizer, and trainer).

# _version_ = 1.0 # they had this in the slides so i just put it here
# from loader import ...
# from visualizer import ...
# from featurizer import ...
# from trainer import ...
